#!/bin/bash

cd ${0%/*} || exit 1    # run from this directory

# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

# Get application directory
application=`getApplication`

./fix-boundary.py

rm -r constant/polyMesh
cp -r constant/polyMesh.inc constant/polyMesh
rotateMesh "(0 1 0)" "(0 0.99904822158 -0.04361938736)"

# runApplication decomposePar

runApplication $application
# runParallel $application

# runApplication postProcess -func sampleDict -latestTime

# runApplication reconstructPar

# runApplication postProcess -fields "(U)" -func rosMag -latestTime